added flags

diff --git a/testAutoCorrect b/testAutoCorrect
--- a/testAutoCorrect
+++ b/testAutoCorrect
@@ -11,13 +11,25 @@ usage() {
   echo "Warning File required"
 }
 
-if [ $# -ne 1 ]; then
+if [ $# -lt 2 ]; then
   usage
   exit 1
 fi
 
-swiftlint lint --strict --reporter emoji --config .swiftlint.yml > $1
+# Parse argument.  $1 is the first argument
+case $1 in
+	"correct")
+	if [ $# -ne 2 ]; then
+  		echo "Path Required"
+  		exit 1
+	fi
+	swiftlint lint --strict --reporter emoji --config .swiftlint.yml --path $2 > error.txt
 
-python AutoLint/AutoCorrect.py $1
+	python AutoLint/AutoCorrect.py error.txt
+	;;
+*)
+    exit 1
+    ;;
+esac
 
-echo "done"
+echo done
